memear/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name = 'core'


urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout_user'),
    path('generate_username_json/', views.generate_username_json, name='generate_username_json'),
]

memear/meme/urls.py
from django.urls import path
from . import views

app_name = 'meme'


urlpatterns = [
    path('new/', views.new_meme, name='new_meme'),
    path('upvote/', views.upvote_meme, name='upvote_meme'),
    path('downvote/', views.downvote_meme, name='downvote_meme'),
    path('memes.json', views.listing_api, name="memes-api"),
]

memear/memear/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('', include('meme.urls')),
    path('admin/', admin.site.urls),
] 

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

memear/meme/models.py
from django.db import models
from django.contrib.auth.models import User
import secrets
import os
import zoneinfo
from datetime import timezone
from django.core.exceptions import ValidationError


ARG = zoneinfo.ZoneInfo('America/Buenos_Aires')


def validate_file_extension(value):
    ext = os.path.splitext(value.name)[1]  # [0] returns path+filename
    valid_extensions = ['.jpg', '.png', '.webp', '.gif', '.bmp', '.jpeg', '.mp4']
    if not ext.lower() in valid_extensions:
        raise ValidationError('Error: Tipo de archivo no soportado.')


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    fext = os.path.splitext(filename)[1]
    return "{0}/{1}".format(instance.created_by.id, f"{secrets.token_hex(10)}{fext}")


class Meme(models.Model):
    title = models.CharField(max_length=100, blank=False, null=False, default='')
    image = models.FileField(upload_to=user_directory_path, blank=False, null=False, validators=[validate_file_extension])
    created_by = models.ForeignKey(User, related_name='memes', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return f"{self.created_by.username}-{self.image.url}"
    
    def fecha(self):
        return self.created_at.replace(tzinfo=timezone.utc).astimezone(ARG).strftime('%d/%m/%y %H:%M')
    
    @property
    def upvotes_count(self):
        return self.votes.filter(vote=True).all().count()
    
    @property
    def downvotes_count(self):
        return self.votes.filter(vote=False).all().count()

    @property
    def net_vote_count(self):
        net_count = self.upvotes_count - self.downvotes_count
        if net_count > 1000:
            return round(net_count, -2) / 1000
        return net_count
        
    def voted(self, user):
        return self.votes.filter(user=user).filter(vote__isnull=False).first() is not None
    
    def upvoted(self, user):
        return self.votes.filter(user=user).filter(vote=True).first() is not None
    
    def downvoted(self, user):
        return self.votes.filter(user=user).filter(vote=False).first() is not None


class Comment(models.Model):
    meme = models.ForeignKey(Meme, related_name='comments', on_delete=models.CASCADE)
    content = models.CharField(max_length=255)


class Vote(models.Model):
    class Meta:
        unique_together = [('meme', 'user')]

    meme = models.ForeignKey(Meme, related_name='votes', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    vote = models.BooleanField(null=True)


from urllib.parse import urlparse
import instaloader

L = instaloader.Instaloader(dirname_pattern=None, save_metadata=False, compress_json=False, download_video_thumbnails=False, post_metadata_txt_pattern='')

def get_shortcode_from_url(url):
    parsed = urlparse(url)
    type, shortcode = parsed.path.split('/')[1:3]
    return type, shortcode


def download_post(shortcode, target):
    L.title_pattern=f'{{typename}}'
    post = instaloader.Post.from_shortcode(L.context, shortcode)
    if L.download_post(post, target=target):
        print(post.title)
        
def delete_file(filename):
    try:
        os.remove(filename)
    except OSError:
        pass

memear/meme/forms.py
from django import forms

from .models import Meme

class NewMemeForm(forms.ModelForm):
    class Meta:
        model = Meme
        fields = ('title', 'image', 'ig_url')

    title = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Un título ingenioso',
        'class': 'w-full py-3 px-6 rounded-xl border dark:border-gray-300 border-gray-600 bg-gray-200 dark:bg-gray-700 text-gray-500 dark:text-gray-400',
    }))

    image = forms.FileField(required=False, widget=forms.FileInput(attrs={
        'class': 'block w-full focus:outline-none absolute inset-0 opacity-0 cursor-pointer',
    }))

    ig_url = forms.URLField(required=False, widget=forms.URLInput(attrs={
        'class': 'w-full py-3 px-6 rounded-xl border dark:border-gray-300 border-gray-600 bg-gray-200 dark:bg-gray-700 text-gray-500 dark:text-gray-400',
    }))

memear/meme/views.py
from django.shortcuts import redirect, render
from django.http import JsonResponse, HttpResponseNotFound, HttpResponseRedirect
from .models import Meme, Vote
from django.contrib.auth.decorators import login_required
from .forms import NewMemeForm
from django.core.paginator import Paginator
from django.db.models import  Q, Count
from meme.models import download_post, get_shortcode_from_url
import os
from django.core.files.images import ImageFile
import io

@login_required
def upvote_meme(request):
    meme_id = request.GET['id']
    meme = Meme.objects.filter(id=meme_id).first()
    if not meme:
        return HttpResponseNotFound("Error")
    vote = Vote.objects.filter(meme=meme).first()
    if vote:
        if vote.vote is True:
            vote.vote = None
        else:
            vote.vote = True
    else:
        vote = Vote(vote=True, meme=meme, user=request.user)
    vote.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    return JsonResponse({'result': 200})


@login_required
def downvote_meme(request):
    meme_id = request.GET['id']
    meme = Meme.objects.filter(id=meme_id).first()
    if not meme:
        return HttpResponseNotFound("Error")
    vote = Vote.objects.filter(meme=meme).first()
    if vote:
        if vote.vote is False:
            vote.vote = None
        else:
            vote.vote = False
    else:
        vote = Vote(vote=False, meme=meme, user=request.user)
    vote.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    return JsonResponse({'result': 200})


@login_required
def new_meme(request):
    if request.method == "POST":
        form = NewMemeForm(request.POST, request.FILES)
        if form.is_valid():
            if form.cleaned_data['ig_url']:
                meme = Meme()
                _, code = get_shortcode_from_url(form.cleaned_data['ig_url'])
                download_post(code, f'dl{request.user.id}')
                with open(os.path.join(f'dl{request.user.id}', os.listdir(f'dl{request.user.id}')[0]), "rb") as fh:
                    buf = io.BytesIO(fh.read())
                image = ImageFile(buf, name=os.listdir(f'dl{request.user.id}')[0])
                meme.image.save(os.listdir(f'dl{request.user.id}')[0], image, save=True)
            else:
                meme = form.save(commit=False)
            meme.created_by = request.user
            meme.save()
            vote = Vote(vote=True, meme=meme, user=request.user)
            vote.save()
            return redirect('/')
    else:
        form = NewMemeForm()
    return render(request, 'meme/new_meme.html', {
        'form': form,
        'title': 'Nuevo Meme'
    })





def listing_api(request):
    page_number = request.GET.get("page", 1)
    per_page = request.GET.get("per_page", 2)
    fresh = int(request.GET.get("fresh")) == 1
    top = int(request.GET.get("top")) == 1
    upvoted = int(request.GET.get("upvoted")) == 1
    if fresh:
        memes = Meme.objects.order_by('-created_at')
    if top:
        memes = Meme.objects.filter(votes__vote=True).annotate(net_votes=Count('votes', filter=Q(votes__vote=True))).order_by('-net_votes').order_by('-created_at')
    if upvoted:
        memes = Meme.objects.filter(votes__user=request.user).filter(votes__vote=True)
    paginator = Paginator(memes, per_page)
    page_obj = paginator.get_page(page_number)
    data = [{"title": meme.title,
            "id": meme.id,
            "upvoted": meme.upvoted(request.user),
            "upvotes_count": meme.upvotes_count,
            "downvotes_count": meme.downvotes_count,
            "net_vote_count": meme.net_vote_count,
            "downvoted": meme.downvoted(request.user),
            "image_url": meme.image.url,
            "pfp_url": meme.created_by.profile.pfp.url,
            "created_by": meme.created_by.username,
            "created_at": meme.fecha()} for meme in page_obj.object_list]
    payload = {
        "page": {
            "current": page_obj.number,
            "has_next": page_obj.has_next(),
            "has_previous": page_obj.has_previous(),
        },
        "data": data,
    }
    return JsonResponse(payload)

memear/meme/templates/meme/new_meme.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

<style>
    .upload-icon {
    fill: rgb(107,114,128)
    }

    .parent-container:hover p, .parent-container:hover .upload-icon {
    color: royalblue;
    fill: royalblue;
    }

    .parent-container:hover {
    border-color: royalblue;
    }
</style>

{% block content %}
    <div class="sm:w-3/4 lg:w-1/2 mx-auto p-6">
        <h1 class="mb-6 text-3xl text-slate-500 dark:text-slate-400">{{ title }}</h1>
        <form method="post" action="." enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
                <label class="inline-block mb-2 font-semibold text-gray-500 dark:text-gray-400">Título</label><br>
                {{ form.title }}
            </div>
            <label class="inline-block mb-2 font-semibold text-gray-500 dark:text-gray-400">Archivo</label><br>
            <div class="parent-container mb-3 cursor-pointer rounded-xl border-dashed border-2 border-gray-400 relative flex justify-center items-center">
                {{ form.image }}
                <div class="w-64 h-20 flex justify-center items-center">
                    <div class="mr-2 text-gray-500 dark:text-gray-400">
                        <svg class="upload-icon" xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-cloud-arrow-up-fill" viewBox="0 0 16 16">
                            <path d="M8 2a5.53 5.53 0 0 0-3.594 1.342c-.766.66-1.321 1.52-1.464 2.383C1.266 6.095 0 7.555 0 9.318 0 11.366 1.708 13 3.781 13h8.906C14.502 13 16 11.57 16 9.773c0-1.636-1.242-2.969-2.834-3.194C12.923 3.999 10.69 2 8 2zm2.354 5.146a.5.5 0 0 1-.708.708L8.5 6.707V10.5a.5.5 0 0 1-1 0V6.707L6.354 7.854a.5.5 0 1 1-.708-.708l2-2a.5.5 0 0 1 .708 0l2 2z"/>
                        </svg>
                    </div>
                    <div>
                        <p class="text-gray-500 dark:text-gray-400 mb-1 text-lg file_name">Subir un archivo</p>
                        <p class="text-xs text-gray-500 dark:text-gray-400"><span class="text-blue-500">elegir uno</span> o soltarlo aquí</p>
                    </div>
                </div>
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2 font-semibold text-gray-500 dark:text-gray-400">...o usar un link de Instagram</label><br>
                {{ form.ig_url }}
            </div>
            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {{ form.non_field_errors }}
                    {{ form.errors }}
                </div>
            {% endif %}
            <button class="my-2 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Crear</button>
        </form>
    </div>
    <script>
        const input_file = document.querySelector('#id_image');
        input_file.addEventListener('change', function(e){
            let file_name = e.target.files[0].name;
            document.querySelector('.file_name').innerText = file_name;
        })
    </script>
{% endblock %}