memear/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name = 'core'


urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout_user'),
    path('generate_username_json/', views.generate_username_json, name='generate_username_json'),
]

memear/meme/urls.py
from django.urls import path
from . import views

app_name = 'meme'


urlpatterns = [
    path('new/', views.new_meme, name='new_meme'),
    path('upvote/', views.upvote_meme, name='upvote_meme'),
    path('downvote/', views.downvote_meme, name='downvote_meme'),
    path('memes.json', views.listing_api, name="memes-api"),
]

memear/memear/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('', include('meme.urls')),
    path('admin/', admin.site.urls),
] 

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

memear/core/models.py
from django.db import models
from django.contrib.auth.models import User
import pydenticon
import hashlib


foreground = [ "rgb(45,79,255)", #AZUL
               "rgb(254,180,44)", #AMARILLO
               "rgb(226,121,234)", #ROSA
               "rgb(30,179,253)", #CELESTE
               "rgb(232,77,65)", #ROJO
               "rgb(255,153,51)", #NARANJA
               "rgb(49,203,115)", #VERDE
               "rgb(141,69,170)" ] #VIOLETA

background = "rgba(255,255,255,0)"

generator = pydenticon.Generator(9, 9, digest=hashlib.sha1,
                                 foreground=foreground, background=background)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    pfp = models.ImageField(default='default.jpg', upload_to='pfps')

    def __str__(self):
        return f'{self.user.username} Profile' 
    
    

memear/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .words import ADVERBIOS, SUSTANTIVOS, ADJETIVOS
import random
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV3


def generate_username():
    sus = random.choice(SUSTANTIVOS).title()
    adv = random.choice(ADVERBIOS).title()
    adj = random.choice(ADJETIVOS).title()
    return f"{sus}{adv}{adj}{random.randint(1,1000)}"


class LoginForm(AuthenticationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'placeholder': 'Su dirección de e-mail',
        'class': 'w-full py-3 px-6 rounded-xl border dark:border-gray-300 border-gray-600 bg-gray-200 dark:bg-gray-700 text-gray-500 dark:text-gray-400',
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Ingrese contraseña',
        'class': 'w-full py-3 px-6 rounded-xl border dark:border-gray-300 border-gray-600 bg-gray-200 dark:bg-gray-700 text-gray-500 dark:text-gray-400',
    }))


class SignUpForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'recaptcha')

    def __init__(self, *args, **kwargs):
            super(SignUpForm, self).__init__(*args, **kwargs)

    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'placeholder': 'Su dirección de e-mail',
        'class': 'w-full py-3 px-6 rounded-xl border dark:border-gray-300 border-gray-600 bg-gray-200 dark:bg-gray-700 text-gray-500 dark:text-gray-400',
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Ingrese contraseña',
        'class': 'w-full py-3 px-6 rounded-xl border dark:border-gray-300 border-gray-600 bg-gray-200 dark:bg-gray-700 text-gray-500 dark:text-gray-400',
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Reingrese contraseña',
        'class': 'w-full py-3 px-6 rounded-xl border dark:border-gray-300 border-gray-600 bg-gray-200 dark:bg-gray-700 text-gray-500 dark:text-gray-400',
    }))
    recaptcha = ReCaptchaField(widget=ReCaptchaV3)

memear/core/views.py
from django.shortcuts import render, redirect
from .models import Profile, generator
from .forms import SignUpForm, generate_username, LoginForm
import io
from django.core.files.images import ImageFile
from django.http import JsonResponse, HttpResponseRedirect
from django.templatetags.static import static
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages


def generate_username_json(request):
    return JsonResponse({'username': generate_username()})


def index(request):
    return render(request, 'core/index.html', {
        'fresh' : int(request.GET.get("fresh", 1)) == 1,
        'top' : int(request.GET.get("top", 0)) == 1,
        'upvoted' : int(request.GET.get("upvoted", 0)) == 1,
    })


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            new_profile = Profile.objects.create(user=new_user)
            identicon_png = generator.generate(new_user.username, 180, 180, output_format="png")
            image = ImageFile(io.BytesIO(identicon_png), name='new_user.id')
            new_profile.pfp.save(f"{new_user.id}.png", image, save=True)
            new_profile.save()
            messages.success(request, 'El usuario se creó correctamente. Inicie sesión.')
            return redirect('/login_user/')
        else:
            print(form.errors)
            messages.error(request, 'Ocurrió un error al crear el usuario.')
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        form = SignUpForm()
    return render(request, 'core/signup.html', {
        'form': form,
        'username': generate_username()
    })


def login_user(request):
    if request.method == 'POST':
        email = request.POST["email"]
        password = request.POST["password"]
        user_object = User.objects.get(email__exact=email)
        username = user_object.username
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user_object)
            return redirect('/')
        else:
            messages.success(request, 'Email o contraseña incorrectos.')
            return redirect('/login_user/')
    else:
        form = LoginForm()
    return render(request, 'core/login.html', {
        'form': form,
    })


def logout_user(request):
    logout(request)
    return redirect('/')

memear/core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Inicio{% endblock %}

{% block content %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    {% if request.user.is_authenticated %}
        <div id="memecontent" class="sm:max-md:pt-3 mt-3 mx-auto py-6"></div>
        <style>
            #loading {
                transition: opacity 1s ease-out;
                opacity: 1;
            }
            .like-arrow {
                position: absolute;
                width: 250px;
                height: 250px;
                top: 0;
                right: 0;
                bottom: 0;
                left: 0;
                margin: auto;
                background: url("{% static 'core/up-256.png' %}") no-repeat center/contain;
                opacity: 0;
                transform: scale(0);
            }

            .meme-img .like-arrow {
                animation-duration: 1000ms;
                animation-name: like-arrow-animation;
                animation-timing-function: ease-in-out;
            }

            @keyframes like-arrow-animation {
                0% {
                    opacity: 0;
                    transform: scale(0);
                }
                15% {
                    opacity: 0.9;
                    transform: scale(1.2);
                }
                30% {
                    transform: scale(0.95);
                }
                45%, 80% {
                    opacity: 0.9;
                    transform: scale(1);
                }
            }
        </style>
        
        <div id="loading">Cargando...</div>
        
        <script>
            function dblTapUpvote(el, mid) {
                el.closest(".meme-img").children[0].classList.add("like-arrow");
                window.location.href = `{% url 'meme:upvote_meme' %}?id=${mid}`;
            }
            async function getData(url, page, paginateBy, fresh=undefined, top=undefined, upvoted=undefined) {
                const urlWithParams = url + "?" + new URLSearchParams({
                    page: page,
                    per_page: paginateBy,
                    fresh: fresh,
                    top: top,
                    upvoted: upvoted
                })
                const response = await fetch(urlWithParams);
                return response.json();
            }
        
            class ScrollMorePaginator {
                constructor(perPage) {
                    this.perPage = perPage
                    this.pageIndex = 1
                    this.lastPage = false
                    this.container = document.querySelector("#memecontent")
                    this.elements = document.querySelectorAll("article")
                    this.loader = document.querySelector("#loading")
                    this.options = {
                        root: null,
                        rootMargin: "0px",
                        threshold: 0.25
                    }
                    this.loadMore()
                    this.watchIntersection()
                }
        
                onIntersect() {
                    if (!this.lastPage) {
                        this.pageIndex++
                        this.loadMore()
                    }
                }
        
                addElement(meme) {
                    let html = `
                        <article class="mx-auto py-6 w-full max-w-3xl">
                            <header class="mb-2 not-format">
                                <h1 class="pb-1 text-3xl font-extrabold dark:text-gray-200 text-gray-800">${meme.title}</h1>
                            </header>
                            <figure>`
                    if (!(meme.upvoted || meme.downvoted)) {
                        html += `<div class="meme-img relative"><div class="arrow"></div><img ondblclick="dblTapUpvote(this, ${meme.id})" class="mx-auto" draggable="false" src="${meme.image_url}" alt=""></div>`
                    } else {
                        html += `<img class="mx-auto" draggable="false" src="${meme.image_url}" alt="">`
                    }
                    html += `<figcaption>
                                    <div class="pt-1 flex items-center gap-1 flex-row">
                                        <div class="flex items-center ">
                                            <div class="p-2 rounded-full dark:border-gray-400 border-gray-800">
                                                <img draggable="false" class="h-5 w-5" src="${meme.pfp_url}" alt="">
                                            </div>
                                        </div>
                                        <div>
                                            <div class="text-xs text-gray-500">${meme.created_by}</div>
                                            <div class="text-xs text-gray-500">${meme.created_at}</div>
                                        </div>
                                    </div>
                                </figcaption>
                                <div class="flex gap-3 justify-end items-center">`
                    if (meme.net_vote_count > 0) {
                        html += `<span class="dark:text-lime-300 text-lime-700 text-md font-semibold">Puntaje: ${meme.net_vote_count}</span>`
                    } else if (meme.net_vote_count < 0) {
                        html += `<span class="dark:text-red-300 text-red-700 text-md font-semibold">Puntaje: ${meme.net_vote_count}</span>`
                    } else {
                        html += `<span class="dark:text-gray-200 text-gray-800 text-md font-semibold">Puntaje: ${meme.net_vote_count}</span>`
                    }
                    if (meme.upvoted || meme.downvoted) {
                        if (meme.upvoted) {
                            html += `<a href="{% url 'meme:upvote_meme' %}?id=${meme.id}" class="px-3 py-2 rounded-full items-center text-md font-semibold bg-lime-700 hover:bg-lime-400 hover:text-gray-700 text-gray-100"><div class="flex items-center gap-2"><i class="fas fa-arrow-up"></i><span class="text-xs"><i class="fas fa-check"></i></span></div></a>
                                            <button disabled class="cursor-not-allowed disabled:opacity-60 px-3 py-2 rounded-full items-center text-md font-semibold bg-red-500"><div class="flex items-center gap-2"><i class="fas fa-arrow-down"></i></div></button>`;
                        } else {
                            html += `<button disabled class="cursor-not-allowed disabled:opacity-60 px-3 py-2 rounded-full items-center text-md font-semibold bg-lime-400"><div class="flex items-center gap-2"><i class="fas fa-arrow-up"></i></div></button>
                                        <a href="{% url 'meme:downvote_meme' %}?id=${meme.id}" class="px-3 py-2 rounded-full items-center text-md font-semibold hover:bg-red-500 bg-red-800 text-gray-100"><div class="flex items-center gap-2"><i class="fas fa-arrow-down"></i><span class="text-xs"><i class="fas fa-check"></i></span></div></a>`;
                        }
                    } else {
                        html += `<a href="{% url 'meme:upvote_meme' %}?id=${meme.id}" class="px-3 py-2 rounded-full items-center text-md font-semibold bg-lime-400 hover:bg-lime-700 hover:text-gray-100"><div class="flex items-center gap-2"><i class="fas fa-arrow-up"></i></div></a>
                                    <a href="{% url 'meme:downvote_meme' %}?id=${meme.id}" class="px-3 py-2 rounded-full items-center text-md font-semibold bg-red-500 hover:bg-red-800 hover:text-gray-100"><div class="flex items-center gap-2"><i class="fas fa-arrow-down"></i></div></a>`;
                    }
                    html += `<a href="#" class="px-3 py-2 rounded-full items-center text-md font-semibold bg-sky-300 hover:bg-sky-700 hover:text-gray-100"><div class="flex items-center gap-2"><i class="fa-solid fa-share-nodes"></i></div></a></div></figure></article>`;
                    this.container.innerHTML += html;
                }
        
                watchIntersection() {
                    document.addEventListener("DOMContentLoaded", () => {
                        const observer = new IntersectionObserver(this.onIntersect.bind(this),
                            this.options);
                        observer.observe(this.loader);
                    })
                }
        
                loadMore() {
                    getData("{% url 'meme:memes-api' %}", 
                        this.pageIndex, 
                        this.perPage,
                        {% if fresh %}1{% else %}0{% endif %},
                        {% if top %}1{% else %}0{% endif %},
                        {% if upvoted %}1{% else %}0{% endif %},
                        )
                        .then(response => {
                            response.data.forEach((el) => {
                                this.addElement(el)
                            });
                            this.loader.style.opacity = !response.page.has_next ? "0" : "1"
                            this.lastPage = !response.page.has_next
                        });
                }
            }

            new ScrollMorePaginator(2);

            var getUrlParameter = function getUrlParameter(sParam) {
                var sPageURL = window.location.search.substring(1),
                    sURLVariables = sPageURL.split('&'),
                    sParameterName,
                    i;

                for (i = 0; i < sURLVariables.length; i++) {
                    sParameterName = sURLVariables[i].split('=');

                    if (sParameterName[0] === sParam) {
                        return sParameterName[1] === undefined ? true : decodeURIComponent(sParameterName[1]);
                    }
                }
                return false;
            };
        </script>
    {% else %}
        <style>
            body {
                overflow: hidden;
            }
        </style>
        <div class="pb-5 h-screen flex w-full items-center justify-center">
            <img class="mx-auto xl:mb-16 xl:pb-16 fixed" draggable="false" src="{% static 'core/logo_text.png' %}">
        </div>
    {% endif %}
{% endblock %}

memear/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Ingresar{% endblock %}

{% block content %}
    <div class="sm:w-3/4 lg:w-1/2 mx-auto p-6">
        <h1 class="mb-6 text-3xl text-slate-500 dark:text-slate-400">Iniciar sesión</h1>
        <form method="post" action=".">
            {% csrf_token %}
            <div class="mb-3">
                <label class="inline-block mb-2 font-semibold text-gray-500 dark:text-gray-400">E-mail</label><br>
                {{ form.email }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2 font-semibold text-gray-500 dark:text-gray-400">Contraseña</label><br>
                {{ form.password }}
            </div>
            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {{ form.errors }}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
            <button class="my-2 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Ingresar</button>
        </form>
    </div>
{% endblock %}

memear/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Registrarse{% endblock %}

{% block content %}
    <div class="sm:w-3/4 lg:w-1/2 mx-auto p-6">
        <h1 class="mb-6 text-3xl text-slate-500 dark:text-slate-400">Registrarse</h1>
        <form method="post" action=".">
            {% csrf_token %}
            <input type="hidden" value="{{ username }}" name="username" id="username_input">
            <div class="mb-3">
                <div class="flex justify-start items-center">
                    <label class="inline-block mb-2 font-semibold text-gray-500 dark:text-gray-400">Nombre de usuario</label><br>
                    <button onclick="new_un()" type="button" role="button" class="dark:text-gray-800 text-gray-200 dark:bg-gray-300 bg-gray-700 hover:bg-gray-500 rounded-full text-sm px-3 py-1 ml-3 mb-1"><i class="fas fa-redo-alt"></i></button>
                </div>
                <div class="flex justify-start items-center">
                    <span id="username_span" class="w-full py-3 px-6 rounded-xl border dark:border-gray-300 border-gray-600 bg-gray-300 dark:bg-gray-700 text-gray-500 dark:text-gray-400">{{ username }}</span>
                </div>
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2 font-semibold text-gray-500 dark:text-gray-400">E-mail</label><br>
                {{ form.email }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2 font-semibold text-gray-500 dark:text-gray-400">Contraseña</label><br>
                {{ form.password1 }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2 font-semibold text-gray-500 dark:text-gray-400">Reingresar contraseña</label><br>
                {{ form.password2 }}
            </div>
            {{ form.recaptcha }}
            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {{ form.errors }}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
            <button class="my-2 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Registrar</button>
        </form>
    </div>
    <script>
        function new_un() {
            async function get_un() {
                const response = await fetch('{% url "core:generate_username_json" %}', {
                    method: 'GET',
                    headers: {
                        'Accept': 'application/json',
                    },
                });
                const json = await response.json();
                return json['username'];
            }
            get_un().then(new_un => {
                document.getElementById("username_input").value = new_un;
                document.getElementById("username_span").innerHTML = new_un;
            });

        }
    </script>
{% endblock %}